spring:
  application:
    name: music-similarity
  datasource:
    url: jdbc:postgresql://localhost:5432/musicdb
    username: postgres
    password: 20012005Kam!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379

spotify:
  client-id: "29de06b2d1ea4491a9a5f2457a63f89b"
  client-secret: "6465ed6e39e74b6e8762b770ece1f7aa"
  api-url: https://api.spotify.com/v1
  auth-url: https://accounts.spotify.com/api/token

server:
  port: 8080

logging:
  level:
    com.musicsimilarity: DEBUG
    org.hibernate.SQL: DEBUG
